use warnings;
use strict;
use Test::More 'no_plan';
use lib '/dm5/ki/adaptive_infrastructure/packages';
require Test::Homebrew_Exception;
require Test::Lists;
use Keithley::Parse::KRF;

my $krf_text = q{
# Keithley Recipe Definition File
Version,1.0
File,LBC5XM__A72AE1BL__M06BL6C598LB0.krf
Date,
Comment,Auto-generated by new adaptive infrastructure
RevID,$Revision: 1.0 $
<EOH>
cpf,dmos5_LBC5X_SLM_r06_AUTO.cpf
wdf,M06BL6C598LB0.wdf
klf,M06BL6C598LB0.klf
usrField2,AAAACMEAAAEgABCgABGNgA
command_line,
<EOR>
};


my $expected_wdf = 'M06BL6C598LB0.wdf';

my $krf = Parse::KRF->new($krf_text);
my $wdf = $krf->get_wdf();

is($wdf, $expected_wdf, "Extract WDF");
